[build]
command = "node --max-old-space-size=4096 pnpm install --no-frozen-lockfile --strict-peer-dependencies=false && pnpm build"
publish = "docs"


[build.environment]
NPM_FLAGS = "--legacy-peer-deps"
