[build]
  command = "npm install -g pnpm@8.15.5 && pnpm install --no-frozen-lockfile --config.strict-peer-dependencies=false && pnpm build"
  publish = "dist"

# 禁用所有语言环境初始化
[build.environment]
  GO_VERSION = "none"
  PHP_VERSION = "none"
  RUBY_VERSION = "none"
  PYTHON_VERSION = "none"