[build]
  command = "echo '跳过构建步骤'"
  publish = "docs"  # 直接发布 docs 目录中的文件
  functions = "docs/functions"  # 若无 Serverless 函数可删除此行

[build.environment]
   NPM_FLAGS = "--ignore-scripts"  # 跳过 npm/pnpm 的依赖安装步骤
   NODE_ENV = "production"         # 可选：阻止安装 devDependencies